from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image, ImageEnhance, ImageFilter


def cover_resize(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    target_w, target_h = size
    scale = max(target_w / image.width, target_h / image.height)
    resized = image.resize((round(image.width * scale), round(image.height * scale)), Image.Resampling.LANCZOS)
    left = max(0, (resized.width - target_w) // 2)
    top = max(0, (resized.height - target_h) // 2)
    return resized.crop((left, top, left + target_w, top + target_h))


def make_cg(source: Path, output: Path, crop_top: int = 0, crop_bottom: int = 0) -> None:
    src = Image.open(source).convert("RGB")
    cropped = src.crop((0, crop_top, src.width, src.height - crop_bottom))
    size = (1920, 1080)
    bg = cover_resize(cropped, size)
    bg = bg.filter(ImageFilter.GaussianBlur(22))
    bg = ImageEnhance.Brightness(bg).enhance(0.55)
    bg = ImageEnhance.Contrast(bg).enhance(1.15)

    fg_scale = min(size[1] / cropped.height, 1060 / cropped.height)
    fg = cropped.resize((round(cropped.width * fg_scale), round(cropped.height * fg_scale)), Image.Resampling.LANCZOS)
    x = (size[0] - fg.width) // 2
    y = (size[1] - fg.height) // 2
    bg.paste(fg, (x, y))
    output.parent.mkdir(parents=True, exist_ok=True)
    bg.save(output, quality=95)
    output.with_suffix(".asset-plan.json").write_text(
        json.dumps(
            {
                "mode": "hui-derived-16x9-adapter",
                "source": str(source),
                "output": str(output),
                "size": list(size),
                "crop_top": crop_top,
                "crop_bottom": crop_bottom,
                "note": "The source image was generated by the locked hui workflow; this step only adapts the final game CG to 16:9.",
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--crop-top", type=int, default=0)
    parser.add_argument("--crop-bottom", type=int, default=0)
    args = parser.parse_args()
    make_cg(Path(args.source), Path(args.output), args.crop_top, args.crop_bottom)


if __name__ == "__main__":
    main()
